name: ci

on:
  push:
    branches:
      - master

jobs:
  demo-site:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 14.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
        working-directory: examples/echo-bot
      - run: yarn build
        working-directory: examples/echo-bot
      - run: yarn add -D netlify-cli
        working-directory: examples/echo-bot
      - run: yarn netlify --telemetry-disable
        working-directory: examples/echo-bot
      - run: yarn netlify deploy --dir=build
        working-directory: examples/echo-bot
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
